/*** CHANGE TO ALLOW GITHUB TO RECOGNIZE THIS AS AN UPDATE ***/

/*
 * Enrollment Breakdown for a term
 * Filtered by TERM
 * Displays the Primary activated academic career program plan information, course information, technology indicator, section component, grade, and GPA information
 *
 */                                          
                                       
select B.UFID, E.TERM_CD, C.ACAD_CAR_LD AS PRIMARY_STDNT_ACAD_CAREER, F.ACAD_ORG_CD AS CLASS_DEPT, F.UF_COURSE_NUMBER, F.CLASS_NBR as SECTION, F.CRSE_LD, F.SSR_COMP_LD, H.INSTRCTN_MODE_LD,  
A.GRADE_PTS , A.TAKEN_UNIT, G.GRADE_CD, A.LAST_ENRL_DTTM_STMP
from CS.WH_F_ENROLLMENT_COURSE A, CS.WH_D_MDM_PERSON B, CS.WH_D_ACAD_CAR C, CS.WH_D_TERM E, CS.WH_D_CLASS F, CS.WH_D_GRADE G, CS.WH_D_INSTRCTN_MODE H 
WHERE A.PERSON_SID = B.PERSON_SID
  AND A.ACAD_CAR_SID = C.ACAD_CAR_SID
  AND A.TERM_SID = E.TERM_SID
  AND A.GRADE_SID = G.GRADE_SID
  AND A.CLASS_SID = F.CLASS_SID
  AND A.INSTRCTN_MODE_SID = H.INSTRCTN_MODE_SID
  AND E.TERM_CD = :1
  order by TERM_CD, UF_COURSE_NUMBER;
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  ---- TEACHING AND TECHNOLOGY ------- CS_VIEWS VERSION OF THE QUERY PROVIDED BY JAMES MARTINEZ
  
select	B.UFID, 
		E.TERM_CD, 
		C.ACAD_CAR_LD AS PRIMARY_STDNT_ACAD_CAREER, 
		F.ACAD_ORG_CD AS CLASS_DEPT,
		F.UF_COURSE_NUMBER, 
		F.CLASS_NUM as SECTION, 
		F.COURSE_LD, 
		--F.SSR_COMP_LD,
		H.INSTRUCTION_MODE_LD,  
		A.GRADE_POINTS, 
		A.HOURS_TAKEN, 
		G.GRADE_CD, 
		A.LAST_ENRLMT_DTTM
		
from	CS_Views.dbo.cv_WH_F_STU_ENRLMT A, 
		CS_Views.dbo.cv_WH_D_MDM_PERSON B, 
		CS_Views.dbo.cv_WH_D_ACAD_CAR C, 
		CS_Views.dbo.cv_WH_D_TERM E, 
		CS_Views.dbo.cv_WH_D_CLASS F,
		CS_Views.dbo.cv_WH_D_GRADE G,
		CS_Views.dbo.cv_WH_D_INSTRUCTION_MODE H
		 
WHERE A.PERSON_SID = B.PERSON_SID						-- ENROLLMENT TO PERSON
  AND A.ACAD_CAR_SID = C.ACAD_CAR_SID					-- ENROLLMENT TO CAREER
  AND A.TERM_SID = E.TERM_SID							-- ENROLLMENT TO TERM
  AND A.GRADE_SID = G.GRADE_SID							-- ENROLLMENT TO GRADE
  AND A.CLASS_SID = F.CLASS_SID							-- ENROLLMENT TO CLASS
  AND A.INSTRUCTION_MODE_SID = H.INSTRUCTION_MODE_SID	-- ENROLLMENT TO DELIVERY
  AND E.TERM_CD = 2188									-- TERM = '20188'
  order by TERM_CD, UF_COURSE_NUMBER;
    
  